### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'output\\Effects'

### ISSUE THREAD

**Issue by DavyJonesKotps** [demberto/FL-PluginDB-Organiser#3]
Every time I run the script I keep getting the error above. Below is what I am running. Any assistance yo get this work would be great.

C:\Temp>fl-plugindb-organiser.exe output
Creating ←[32mEffects←[0m folder
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Temp\fl-plugindb-organiser.exe\__main__.py", line 7, in <module>
  File "C:\Users\Wolf Jones\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fl_plugin_db_organiser\__init__.py", line 249, in main
    fl_plugin_db_organiser(output_dir, log, args.no_color)
  File "C:\Users\Wolf Jones\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fl_plugin_db_organiser\__init__.py", line 89, in fl_plugin_db_organiser
    effects.mkdir()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'output\\Effects'

**Comment by demberto** [comment]
How did you run it? In which folder?

**Comment by DavyJonesKotps** [comment]
After reading the steps over again I was able to figure out what I was doing wrong. Thank you for reaching back out to me.

**Comment by demberto** [comment]
Glad, that you worked it out :)
